# -*- coding: utf-8 -*-
"""v20 LiCEnSURE RF Classifier ready for integration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXph8EQFBP07u0Hc02ZK014uOWtrUsj8

# Random Forest CELE/Licensure Prediction Notebook

This Colab notebook performs an end-to-end **classification workflow** for licensure-exam outcome prediction with **FAILED as the positive class**.

## What this notebook does
1. Mounts Google Drive and loads the dataset
2. Performs EDA and missing-value inspection
3. Applies **necessary preprocessing** without dropping feature columns with `N/A` values
4. Uses:
   - **One-Hot Encoding** for categorical predictor columns
   - **Label Encoding** for the target column
   - **Imputation** for missing values
5. Tunes a **Random Forest** model
6. Validates using **10-fold cross-validation**
7. Displays **per-fold metrics** for all 10 iterations
8. Reports:
   - Confusion Matrix
   - Accuracy
   - Precision
   - Recall
   - Specificity
   - F1-score
   - ROC-AUC
9. Fits a final tuned model and displays **SHAP strong predictor feature importance**

> **Important:** Update the configuration cell before running the notebook.
"""

# Commented out IPython magic to ensure Python compatibility.
# Install SHAP if needed
# %pip -q install shap

import warnings
warnings.filterwarnings("ignore")

import json
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from IPython.display import display

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    make_scorer
)
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.ensemble import RandomForestClassifier

import shap

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 200)
pd.set_option("display.max_colwidth", 120)

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# =========================
# CONFIGURATION
# =========================

# Example:
FILE_PATH = '/content/drive/MyDrive/v7 LiCEnSURE Dataset.csv'

TARGET_COLUMN = 'Result'

POSITIVE_CLASS_NAME = 'FAILED'

# Optional: columns to exclude from predictors if they are IDs / names / obvious leakage columns
COLUMNS_TO_EXCLUDE = []

# Random Forest hyperparameter search setup
N_ITER_SEARCH = 20          # number of random parameter combinations per search
INNER_CV_FOLDS = 3          # inner CV for tuning inside each outer fold
OUTER_CV_FOLDS = 10         # required 10-fold validation
SCORING_METRIC = 'recall_failed'   # optimize recall for FAILED class

# SHAP settings
SHAP_SAMPLE_SIZE = 500      # automatically reduced if dataset is smaller
TOP_N_SHAP = 20

print("Update FILE_PATH and TARGET_COLUMN before running the next cells.")

# Load dataset
df = pd.read_csv(FILE_PATH, encoding='latin1')

print(f"Dataset shape: {df.shape}")
display(df.head())

# Standardize common missing-value markers WITHOUT dropping feature columns
missing_markers = [
    '', ' ', '  ', 'N/A', 'n/a', 'NA', 'na', 'NaN', 'nan',
    'NULL', 'null', 'None', 'none', '?', '-', '--'
]

df = df.replace(missing_markers, np.nan)

print("Dataset info:")
display(df.info())

print("\nMissing values per column:")
missing_summary = df.isna().sum().sort_values(ascending=False)
display(missing_summary[missing_summary > 0])

print("\nTarget preview:")
display(df[TARGET_COLUMN].value_counts(dropna=False))

# Basic EDA
print("First 5 rows:")
display(df.head())

print("\nDescriptive statistics for numeric columns:")
display(df.describe(include=[np.number]).T)

print("\nCategorical columns preview:")
cat_cols_preview = df.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()
if cat_cols_preview:
    preview_df = pd.DataFrame({
        'column': cat_cols_preview,
        'unique_values': [df[c].nunique(dropna=True) for c in cat_cols_preview],
        'missing_values': [df[c].isna().sum() for c in cat_cols_preview]
    }).sort_values(by='unique_values', ascending=False)
    display(preview_df)
else:
    print("No categorical columns detected.")

# Plot target distribution
plt.figure(figsize=(7, 4))
target_counts = df[TARGET_COLUMN].astype(str).value_counts(dropna=False)
plt.bar(target_counts.index.astype(str), target_counts.values)
plt.title('Target Class Distribution')
plt.xlabel(TARGET_COLUMN)
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Optional: quick visual check of top missing columns
top_missing = missing_summary[missing_summary > 0].head(20)

if len(top_missing) > 0:
    plt.figure(figsize=(10, 5))
    plt.barh(top_missing.index[::-1], top_missing.values[::-1])
    plt.title('Top Columns with Missing Values')
    plt.xlabel('Missing Count')
    plt.tight_layout()
    plt.show()
else:
    print("No missing values found in the dataset.")

# Prepare target and features
if TARGET_COLUMN not in df.columns:
    raise ValueError(f"TARGET_COLUMN '{TARGET_COLUMN}' is not found in the dataset.")

# Remove rows with missing target only if necessary
target_missing_count = df[TARGET_COLUMN].isna().sum()
if target_missing_count > 0:
    print(f"Rows with missing target: {target_missing_count}")
    df = df.loc[df[TARGET_COLUMN].notna()].copy()
    print(f"New dataset shape after removing rows with missing target only: {df.shape}")

# Clean target labels
y_raw = df[TARGET_COLUMN].astype(str).str.strip()
X = df.drop(columns=[TARGET_COLUMN] + [c for c in COLUMNS_TO_EXCLUDE if c in df.columns]).copy()

# Determine unique target classes
target_classes_raw = y_raw.unique()

if len(target_classes_raw) != 2:
    raise ValueError("This notebook currently supports binary classification only.")

# Identify the positive and negative class names based on POSITIVE_CLASS_NAME
positive_class_original = [
    cls for cls in target_classes_raw
    if str(cls).strip().lower() == POSITIVE_CLASS_NAME.strip().lower()
]

if len(positive_class_original) != 1:
    raise ValueError(
        f"Could not uniquely identify the positive class '{POSITIVE_CLASS_NAME}'. "
        f"Available classes: {list(target_classes_raw)}"
    )
positive_class_original = positive_class_original[0]

negative_class_original = [cls for cls in target_classes_raw if cls != positive_class_original][0]

# Define the desired mapping: POSITIVE_CLASS_NAME -> 1, other class -> 0
custom_label_map = {
    positive_class_original: 1,
    negative_class_original: 0
}

# Apply the custom mapping to y_raw to create the encoded target array y
y = y_raw.map(custom_label_map).values

# Set POS_LABEL and NEG_LABEL based on the custom mapping
POS_LABEL = custom_label_map[positive_class_original]
NEG_LABEL = custom_label_map[negative_class_original]

# Create a LabelEncoder-like object for consistency in inverse_transform later
# This ensures inverse_transform(0) gives negative_class and inverse_transform(1) gives positive_class
class PseudoLabelEncoder:
    def __init__(self, neg_class, pos_class):
        self.classes_ = np.array([neg_class, pos_class]) # Order matters for inverse_transform

    def inverse_transform(self, encoded_labels):
        return self.classes_[np.array(encoded_labels).astype(int)]

label_encoder = PseudoLabelEncoder(negative_class_original, positive_class_original)


# Create class_map_df for display using the custom mapping
class_map_df = pd.DataFrame({
    'original_class': [negative_class_original, positive_class_original],
    'encoded_label': [NEG_LABEL, POS_LABEL]
})

print("Encoded target classes (custom mapping):")
display(class_map_df)


print(f"Positive class ({POSITIVE_CLASS_NAME}): '{positive_class_original}' -> encoded as {POS_LABEL}")
print(f"Negative class: '{negative_class_original}' -> encoded as {NEG_LABEL}")

# Identify feature types
numeric_features = X.select_dtypes(include=[np.number]).columns.tolist()
categorical_features = [col for col in X.columns if col not in numeric_features]

print(f"Number of predictor columns: {X.shape[1]}")
print(f"Numeric features: {len(numeric_features)}")
print(f"Categorical features: {len(categorical_features)}")

# Build preprocessing pipeline
try:
    ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
except TypeError:
    ohe = OneHotEncoder(handle_unknown='ignore', sparse=False)

numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median'))
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', ohe)
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='drop'
)

base_model = RandomForestClassifier(
    random_state=RANDOM_STATE,
    class_weight='balanced',
    n_jobs=-1
)

pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', base_model)
])

param_distributions = {
    'model__n_estimators': [100, 200, 300, 500, 700],
    'model__max_depth': [None, 5, 10, 15, 20, 30],
    'model__min_samples_split': [2, 5, 10, 15],
    'model__min_samples_leaf': [1, 2, 4, 6],
    'model__max_features': ['sqrt', 'log2', None],
    'model__bootstrap': [True, False]
}

recall_failed_scorer = make_scorer(recall_score, pos_label=POS_LABEL)

print("Pipeline and parameter search space are ready.")

# Helper function to compute requested metrics
def compute_binary_metrics(y_true, y_pred, y_prob, pos_label, neg_label):
    cm = confusion_matrix(y_true, y_pred, labels=[neg_label, pos_label])
    tn, fp, fn, tp = cm.ravel()

    specificity = tn / (tn + fp) if (tn + fp) > 0 else np.nan
    roc_auc = roc_auc_score(y_true, y_prob) if len(np.unique(y_true)) == 2 else np.nan

    return {
        'TN': tn,
        'FP': fp,
        'FN': fn,
        'TP': tp,
        'accuracy': accuracy_score(y_true, y_pred),
        'precision': precision_score(y_true, y_pred, pos_label=pos_label, zero_division=0),
        'recall': recall_score(y_true, y_pred, pos_label=pos_label, zero_division=0),
        'specificity': specificity,
        'f1_score': f1_score(y_true, y_pred, pos_label=pos_label, zero_division=0),
        'roc_auc': roc_auc
    }

"""## Nested 10-Fold Cross-Validation with Hyperparameter Tuning

This section performs:

- **Outer 10-fold cross-validation** for evaluation
- **Inner CV hyperparameter tuning** on each training fold
- Metric reporting for **each fold / iteration**
- **FAILED** is treated as the positive class throughout the workflow

"""

outer_cv = StratifiedKFold(n_splits=OUTER_CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)
inner_cv = StratifiedKFold(n_splits=INNER_CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)

fold_results = []
oof_pred = np.zeros(len(y), dtype=int)
oof_prob = np.zeros(len(y), dtype=float)

for fold_idx, (train_idx, test_idx) in enumerate(outer_cv.split(X, y), start=1):
    print(f"\n{'='*80}")
    print(f"Fold {fold_idx}/{OUTER_CV_FOLDS}")
    print(f"{'='*80}")

    X_train, X_test = X.iloc[train_idx].copy(), X.iloc[test_idx].copy()
    y_train, y_test = y[train_idx], y[test_idx]

    search = RandomizedSearchCV(
        estimator=pipeline,
        param_distributions=param_distributions,
        n_iter=N_ITER_SEARCH,
        scoring=recall_failed_scorer,
        cv=inner_cv,
        random_state=RANDOM_STATE + fold_idx,
        n_jobs=-1,
        refit=True,
        verbose=0
    )

    search.fit(X_train, y_train)
    best_model = search.best_estimator_

    y_pred = best_model.predict(X_test)
    y_prob = best_model.predict_proba(X_test)[:, POS_LABEL]

    oof_pred[test_idx] = y_pred
    oof_prob[test_idx] = y_prob

    metrics = compute_binary_metrics(y_test, y_pred, y_prob, pos_label=POS_LABEL, neg_label=NEG_LABEL)
    metrics['fold'] = fold_idx
    metrics['train_size'] = len(train_idx)
    metrics['test_size'] = len(test_idx)
    metrics['best_score_inner_cv_recall_failed'] = search.best_score_
    metrics['best_params'] = json.dumps(search.best_params_)

    fold_results.append(metrics)

fold_results_df = pd.DataFrame(fold_results)

ordered_cols = [
    'fold', 'train_size', 'test_size',
    'TN', 'FP', 'FN', 'TP',
    'accuracy', 'precision', 'recall', 'specificity', 'f1_score', 'roc_auc',
    'best_score_inner_cv_recall_failed', 'best_params'
]
fold_results_df = fold_results_df[ordered_cols]

print("\nPer-fold results:")
display(fold_results_df)

# Per-fold summary statistics
metric_cols = ['accuracy', 'precision', 'recall', 'specificity', 'f1_score', 'roc_auc']

summary_df = pd.DataFrame({
    'Metric': metric_cols,
    'Mean': [fold_results_df[m].mean() for m in metric_cols],
    'Std': [fold_results_df[m].std() for m in metric_cols],
    'Min': [fold_results_df[m].min() for m in metric_cols],
    'Max': [fold_results_df[m].max() for m in metric_cols]
})

print("10-fold summary statistics:")
display(summary_df)

# Overall out-of-fold evaluation across all 10 folds
overall_metrics = compute_binary_metrics(y, oof_pred, oof_prob, pos_label=POS_LABEL, neg_label=NEG_LABEL)
overall_cm = confusion_matrix(y, oof_pred, labels=[NEG_LABEL, POS_LABEL])

overall_metrics_df = pd.DataFrame([overall_metrics]).T.reset_index()
overall_metrics_df.columns = ['metric', 'value']

print("Overall out-of-fold metrics:")
display(overall_metrics_df)

print("\nOverall confusion matrix (rows=true, cols=predicted):")
cm_df = pd.DataFrame(
    overall_cm,
    index=[f"Actual_{label_encoder.inverse_transform([NEG_LABEL])[0]}", f"Actual_{label_encoder.inverse_transform([POS_LABEL])[0]}"],
    columns=[f"Pred_{label_encoder.inverse_transform([NEG_LABEL])[0]}", f"Pred_{label_encoder.inverse_transform([POS_LABEL])[0]}"]
)
display(cm_df)

plt.figure(figsize=(5, 4))
plt.imshow(overall_cm, interpolation='nearest')
plt.title('Overall Out-of-Fold Confusion Matrix')
plt.colorbar()
tick_marks = np.arange(2)
plt.xticks(tick_marks, [label_encoder.inverse_transform([NEG_LABEL])[0], label_encoder.inverse_transform([POS_LABEL])[0]])
plt.yticks(tick_marks, [label_encoder.inverse_transform([NEG_LABEL])[0], label_encoder.inverse_transform([POS_LABEL])[0]])
plt.xlabel('Predicted label')
plt.ylabel('True label')

for i in range(overall_cm.shape[0]):
    for j in range(overall_cm.shape[1]):
        plt.text(j, i, overall_cm[i, j], ha='center', va='center')

plt.tight_layout()
plt.show()

print("Classification report using out-of-fold predictions:")
print(classification_report(
    y,
    oof_pred,
    target_names=label_encoder.inverse_transform([NEG_LABEL, POS_LABEL]),
    zero_division=0
))

"""## Final Hyperparameter Tuning on the Full Dataset

After cross-validation evaluation, this section tunes a final model on the **entire dataset** using **10-fold CV**, then uses the final tuned model for SHAP interpretation.

"""

final_cv = StratifiedKFold(n_splits=OUTER_CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)

final_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_distributions,
    n_iter=N_ITER_SEARCH,
    scoring=recall_failed_scorer,
    cv=final_cv,
    random_state=RANDOM_STATE,
    n_jobs=-1,
    refit=True,
    verbose=0
)

final_search.fit(X, y)
final_model = final_search.best_estimator_

print("Best parameters from final 10-fold tuning:")
display(pd.DataFrame([final_search.best_params_]))

print(f"Best 10-fold CV recall for FAILED: {final_search.best_score_:.4f}")

"""## SHAP Strong Predictors Feature Importance

This section displays the strongest predictors using SHAP values for the **FAILED** class.

"""

# Transform data for SHAP
fitted_preprocessor = final_model.named_steps['preprocessor']
fitted_rf = final_model.named_steps['model']

feature_names = fitted_preprocessor.get_feature_names_out()

sample_size = min(SHAP_SAMPLE_SIZE, len(X))
X_shap_sample = X.sample(n=sample_size, random_state=RANDOM_STATE).copy()
X_shap_transformed = fitted_preprocessor.transform(X_shap_sample)

# Compute SHAP values
explainer = shap.TreeExplainer(fitted_rf)
shap_values = explainer.shap_values(X_shap_transformed)

# Support different SHAP output formats
if isinstance(shap_values, list):
    shap_values_pos = shap_values[POS_LABEL]
elif isinstance(shap_values, np.ndarray):
    if shap_values.ndim == 3:
        shap_values_pos = shap_values[:, :, POS_LABEL]
    else:
        shap_values_pos = shap_values
else:
    raise ValueError("Unsupported SHAP output format.")

# Aggregate mean absolute SHAP values
shap_importance_df = pd.DataFrame({
    'feature': feature_names,
    'mean_abs_shap': np.abs(shap_values_pos).mean(axis=0)
}).sort_values(by='mean_abs_shap', ascending=False).reset_index(drop=True)

print(f"Top {TOP_N_SHAP} SHAP strong predictors for FAILED:")
display(shap_importance_df.head(TOP_N_SHAP))

# Plot top 10 SHAP strong predictors
TOP_10 = 10
top_shap = shap_importance_df.head(TOP_10).sort_values(by='mean_abs_shap', ascending=True)

plt.figure(figsize=(10, 6))
plt.barh(top_shap['feature'], top_shap['mean_abs_shap'], color='skyblue')
plt.title(f'Top {TOP_10} SHAP Strong Predictors for FAILED')
plt.xlabel('Mean |SHAP value|')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import shap

# Using the variables computed in the previous SHAP cell
# shap_values_pos, X_shap_transformed, and feature_names are already in the kernel

# Resized the figure to be smaller
plt.figure(figsize=(6, 4))
shap.summary_plot(
    shap_values_pos,
    X_shap_transformed,
    feature_names=feature_names,
    max_display=10,
    show=False
)
plt.title('Top 10 Predictors for FAILED (SHAP Summary)')
plt.tight_layout()
plt.show()

"""## Notes

- This notebook **does not drop feature columns with `N/A` values**.
- Missing values are handled through **imputation**:
  - **Median** for numeric predictors
  - **Most frequent** for categorical predictors
- The target is **Label Encoded**
- Categorical predictors are **One-Hot Encoded**
- The model is tuned and evaluated with **FAILED as the positive class**
- The tuning objective is **recall for FAILED**, which is useful for early warning scenarios

"""