# -*- coding: utf-8 -*-
"""v18 LiCEnSURE for docu ni.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fbg_Cx36a6dqpO5Re1ByNKXDbIpTM4oF

# Import Libraries

This notebook keeps the original flow but fixes the leakage issues and adds a **two-stage / cascade classification** setup.

### Goal
- **Positive class = FAILED (1)**
- prioritize **Recall for FAILED**
- minimize **False Negatives (FN)**
- still check **Precision** and **Specificity** so the system stays usable
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import shap

# Machine Learning Imports
from sklearn.model_selection import train_test_split, StratifiedKFold, RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from xgboost import XGBClassifier
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, make_scorer, roc_auc_score
)
from sklearn.base import clone
from scipy.stats import randint, uniform
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE

# Visualization settings
# %matplotlib inline
warnings.filterwarnings('ignore')
sns.set_theme(style="whitegrid")

RANDOM_STATE = 42

"""# Load dataset"""

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# File path
file_path = '/content/drive/MyDrive/v7 LiCEnSURE Dataset.csv'

# Load the dataset
try:
    df = pd.read_csv(file_path, encoding='latin-1')
    print('Dataset loaded successfully!')
    display(df.head())
except Exception as e:
    print(f'Error: {e}')

print('--- Dataset Information ---')
df.info()

print('\n--- Descriptive Statistics ---')
display(df.describe(include='all'))

print('\n--- Missing Values Count ---')
display(df.isnull().sum().sort_values(ascending=False).head(15))

if 'Result' in df.columns:
    print('\n--- Target Distribution ---')
    display(df['Result'].astype(str).str.strip().str.upper().value_counts())

# Visualize distributions of numerical features
print('\n--- Histograms of Numerical Features ---')
plt.figure(figsize=(15, 10))
num_cols_preview = df.select_dtypes(include=['number']).columns
for i, col in enumerate(num_cols_preview[:6]):
    plt.subplot(2, 3, i + 1)
    sns.histplot(df[col].dropna(), kde=True)
    plt.title(f'Distribution of {col}')
plt.tight_layout()
plt.show()

# Visualize counts of categorical features
print('\n--- Count Plots of Categorical Features ---')
plt.figure(figsize=(15, 5))
cat_cols_preview = df.select_dtypes(exclude=['number']).columns
for i, col in enumerate(cat_cols_preview[:3]):
    plt.subplot(1, 3, i + 1)
    sns.countplot(y=df[col].astype(str), order=df[col].astype(str).value_counts().index[:10])
    plt.title(f'Count of {col}')
plt.tight_layout()
plt.show()

"""#EDA for paper"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# 1. Class Distribution - Resized smaller
plt.figure(figsize=(6, 4))
sns.countplot(x=y, palette='viridis')
plt.title('Target Class Distribution (0: PASSED, 1: FAILED)')
plt.xlabel('Result')
plt.ylabel('Count')
plt.show()

# 2. Correlation Heatmap - Resized smaller
plt.figure(figsize=(8, 6))
corr_matrix = df.select_dtypes(include=[np.number]).corr()
sns.heatmap(corr_matrix, annot=True, cmap='RdBu_r', fmt='.2f', linewidths=0.5, annot_kws={'size': 8})
plt.title('Feature Correlation Heatmap')
plt.show()

# 3. Descriptive Summary Table
print('\n--- Numerical Features Summary ---')
display(df.describe().T)

"""# Preprocessing"""

# Load dataset again
df = pd.read_csv(file_path, encoding='latin-1')

# Clean column names
df.columns = df.columns.str.strip()

# Target variable
if 'Result' in df.columns and 'Fail' not in df.columns:
    df['Fail'] = df['Result'].apply(lambda x: 1 if str(x).strip().upper() == 'FAILED' else 0)

# Drop obvious non-predictors if they exist
cols_to_drop = ['Student_Code', 'Student_ID', 'Student_Name', 'Result', 'Unnamed: 15']
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns], errors='ignore')

# Optional cleaning for suspicious Age values
if 'Age' in df.columns:
    df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
    df.loc[(df['Age'] < 10) | (df['Age'] > 100), 'Age'] = np.nan

# Separate features and target
if 'Fail' not in df.columns:
    raise ValueError("Target column 'Fail' was not created. Please check the dataset.")

X = df.drop('Fail', axis=1).copy()
y = df['Fail'].astype(int).copy()

# Identify column types
num_cols = X.select_dtypes(include=['number']).columns.tolist()
cat_cols = X.select_dtypes(exclude=['number']).columns.tolist()

print('Preprocessing setup complete.')
print(f'Total rows: {len(df)}')
print(f'Total features: {X.shape[1]}')
print(f'Numerical columns: {len(num_cols)}')
print(f'Categorical columns: {len(cat_cols)}')
print(f'FAILED count: {(y == 1).sum()}')
print(f'PASSED count: {(y == 0).sum()}')

display(X.head())

"""# Candidate models"""

from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

def get_ohe():
    try:
        return OneHotEncoder(handle_unknown='ignore', sparse_output=False)
    except TypeError:
        return OneHotEncoder(handle_unknown='ignore', sparse=False)

def get_models():
    return {
        "Logistic Regression": LogisticRegression(
            max_iter=1000,
            solver='lbfgs',
            random_state=RANDOM_STATE
        ),
        "Decision Tree": DecisionTreeClassifier(
            max_depth=10,
            random_state=RANDOM_STATE
        ),
        "Random Forest": RandomForestClassifier(
            n_estimators=300,
            max_depth=10,
            random_state=RANDOM_STATE
        ),
        "Gradient Boosting": GradientBoostingClassifier(
            n_estimators=150,
            learning_rate=0.05,
            max_depth=3,
            random_state=RANDOM_STATE
        ),
        "XGBoost": XGBClassifier(
            n_estimators=300,
            max_depth=4,
            learning_rate=0.05,
            subsample=0.8,
            colsample_bytree=0.8,
            eval_metric='logloss',
            random_state=RANDOM_STATE
        ),
        "SVC": SVC(
            probability=True,
            kernel='rbf',
            random_state=RANDOM_STATE
        ),
        "Neural Network": MLPClassifier(
            max_iter=1000,
            random_state=RANDOM_STATE
        )
    }

def get_param_distributions():
    return {
        "Logistic Regression": {
            'model__C': uniform(0.01, 5.0),
            'model__class_weight': [None, 'balanced']
        },
        "Decision Tree": {
            'model__max_depth': [None, 5, 10, 15, 20],
            'model__min_samples_split': randint(2, 20),
            'model__min_samples_leaf': randint(1, 10),
            'model__criterion': ['gini', 'entropy']
        },
        "Random Forest": {
            'model__n_estimators': randint(200, 700),
            'model__max_depth': [None, 4, 6, 8, 10, 12],
            'model__min_samples_split': randint(2, 10),
            'model__min_samples_leaf': randint(1, 5),
            'model__max_features': ['sqrt', 'log2', None],
            'model__class_weight': [None, 'balanced', 'balanced_subsample']
        },
        "Gradient Boosting": {
            'model__n_estimators': randint(100, 400),
            'model__learning_rate': uniform(0.01, 0.20),
            'model__max_depth': randint(2, 5),
            'model__min_samples_split': randint(2, 10),
            'model__min_samples_leaf': randint(1, 5),
            'model__subsample': uniform(0.7, 0.3)
        },
        "XGBoost": {
            'model__n_estimators': randint(200, 500),
            'model__max_depth': randint(2, 6),
            'model__learning_rate': uniform(0.01, 0.20),
            'model__subsample': uniform(0.7, 0.3),
            'model__colsample_bytree': uniform(0.7, 0.3),
            'model__gamma': uniform(0.0, 0.5),
            'model__reg_lambda': uniform(1.0, 5.0)
        },
        "SVC": {
            'model__C': uniform(0.1, 10.0),
            'model__gamma': ['scale', 'auto', 0.1, 0.01],
            'model__class_weight': [None, 'balanced']
        },
        "Neural Network": {
            'model__hidden_layer_sizes': [(50,), (100,), (50, 50), (100, 50)],
            'model__activation': ['relu', 'tanh'],
            'model__alpha': uniform(0.0001, 0.05),
            'model__learning_rate_init': uniform(0.001, 0.01)
        }
    }

def build_pipeline(model_name, estimator=None, use_lda=False):
    if estimator is None:
        estimator = get_models()[model_name]
    numeric_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median'))])
    categorical_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')), ('encoder', get_ohe())])
    preprocessor = ColumnTransformer(transformers=[('num', numeric_transformer, num_cols), ('cat', categorical_transformer, cat_cols)], remainder='drop')
    needs_scaling = (model_name in ['Logistic Regression', 'SVC', 'Neural Network', 'Decision Tree']) or use_lda
    pipe = Pipeline(steps=[('preprocessor', preprocessor), ('scaler', StandardScaler() if needs_scaling else 'passthrough'), ('lda', LinearDiscriminantAnalysis() if use_lda else 'passthrough'), ('smote', SMOTE(random_state=RANDOM_STATE)), ('model', clone(estimator))])
    return pipe

from sklearn.tree import DecisionTreeClassifier

def get_models_updated():
    models = get_models()
    models["Decision Tree"] = DecisionTreeClassifier(
        max_depth=10,
        random_state=RANDOM_STATE
    )
    return models

def get_param_distributions_updated():
    params = get_param_distributions()
    params["Decision Tree"] = {
        'model__max_depth': [None, 5, 10, 15, 20],
        'model__min_samples_split': randint(2, 20),
        'model__min_samples_leaf': randint(1, 10),
        'model__criterion': ['gini', 'entropy']
    }
    return params

"""# Model evaluation"""

def get_metrics(y_true, y_pred, y_pred_proba=None):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()

    metrics = {
        'Accuracy': accuracy_score(y_true, y_pred),
        'Precision': precision_score(y_true, y_pred, zero_division=0),
        'Recall': recall_score(y_true, y_pred, zero_division=0),
        'Specificity': tn / (tn + fp) if (tn + fp) > 0 else 0,
        'F1-score': f1_score(y_true, y_pred, zero_division=0),
        'TN': tn,
        'FP': fp,
        'FN': fn,
        'TP': tp
    }
    if y_pred_proba is not None:
        metrics['ROC AUC'] = roc_auc_score(y_true, y_pred_proba)
    return metrics

def evaluate_model_cv(X, y, model_name, estimator=None, use_lda=False, cv=None):
    if cv is None:
        cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)

    if estimator is None:
        estimator = get_models()[model_name]

    fold_results = []

    print(f'Running 10-fold CV for: {model_name} | {"With LDA" if use_lda else "Baseline"}')

    for fold, (train_idx, test_idx) in enumerate(cv.split(X, y), start=1):
        X_train_fold = X.iloc[train_idx].copy()
        X_test_fold = X.iloc[test_idx].copy()
        y_train_fold = y.iloc[train_idx].copy()
        y_test_fold = y.iloc[test_idx].copy()

        pipe = build_pipeline(model_name, estimator=estimator, use_lda=use_lda)
        pipe.fit(X_train_fold, y_train_fold)
        y_pred_fold = pipe.predict(X_test_fold)
        y_pred_proba_fold = pipe.predict_proba(X_test_fold)[:, 1]

        row = {'Fold': fold}
        row.update(get_metrics(y_test_fold, y_pred_fold, y_pred_proba_fold))
        fold_results.append(row)

    fold_results_df = pd.DataFrame(fold_results)

    summary = {
        'Model': model_name,
        'Method': 'With LDA' if use_lda else 'Baseline',
        'Accuracy': fold_results_df['Accuracy'].mean(),
        'Precision': fold_results_df['Precision'].mean(),
        'Recall': fold_results_df['Recall'].mean(),
        'Specificity': fold_results_df['Specificity'].mean(),
        'F1-score': fold_results_df['F1-score'].mean(),
        'ROC AUC': fold_results_df['ROC AUC'].mean(),
        'TN': fold_results_df['TN'].mean(),
        'FP': fold_results_df['FP'].mean(),
        'FN': fold_results_df['FN'].mean(),
        'TP': fold_results_df['TP'].mean(),
        'Std Recall': fold_results_df['Recall'].std(),
        'Std F1': fold_results_df['F1-score'].std()
    }

    return pd.DataFrame([summary]), fold_results_df

"""# Baseline comparison using the same CV logic"""

cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)

baseline_results = []
baseline_fold_logs = {}

# Loop through all models which now includes SVC and Neural Network
for model_name in get_models().keys():
    for use_lda in [False, True]:
        summary_df, fold_df = evaluate_model_cv(X, y, model_name, use_lda=use_lda, cv=cv)
        baseline_results.append(summary_df)
        baseline_fold_logs[f'{model_name} | {"With LDA" if use_lda else "Baseline"}'] = fold_df

baseline_results_df = pd.concat(baseline_results, ignore_index=True)
baseline_results_df = baseline_results_df.sort_values(
    by=['Recall', 'FN', 'F1-score', 'Precision', 'Specificity'],
    ascending=[False, True, False, False, False]
).reset_index(drop=True)

print('--- Baseline Results ---')
display(baseline_results_df)

candidate_configs = baseline_results_df[['Model', 'Method']].drop_duplicates().head(4).reset_index(drop=True)

print('--- Top 4 Candidate Configurations for Tuning ---')
display(candidate_configs)

"""# Tune only the final candidate models"""

recall_failed_scorer = make_scorer(recall_score, pos_label=1)

def tune_model(X, y, model_name, use_lda=False, n_iter=12):
    base_model = get_models()[model_name]
    pipe = build_pipeline(model_name, estimator=base_model, use_lda=use_lda)

    search = RandomizedSearchCV(
        estimator=pipe,
        param_distributions=get_param_distributions()[model_name],
        n_iter=n_iter,
        scoring=recall_failed_scorer,
        cv=StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE),
        n_jobs=-1,
        random_state=RANDOM_STATE,
        refit=True,
        verbose=1
    )

    search.fit(X, y)
    return search

tuned_searches = {}
tuned_results = []

# Filter candidate configs for the ones selected from baseline
for _, row in candidate_configs.iterrows():
    model_name = row['Model']
    method_name = row['Method']
    use_lda = (method_name == 'With LDA')

    print('\n========================================')
    print(f'Tuning: {model_name} | {method_name}')
    print('========================================')

    search = tune_model(X, y, model_name, use_lda=use_lda, n_iter=12)
    tuned_searches[(model_name, method_name)] = search

    tuned_model = clone(search.best_estimator_.named_steps['model'])
    summary_df, _ = evaluate_model_cv(X, y, model_name, estimator=tuned_model, use_lda=use_lda, cv=cv)

    summary_df['Best Recall from Search'] = search.best_score_
    summary_df['Best Params'] = str(search.best_params_)
    tuned_results.append(summary_df)

tuned_results_df = pd.concat(tuned_results, ignore_index=True)
tuned_results_df = tuned_results_df.sort_values(
    by=['Recall', 'FN', 'F1-score', 'Precision', 'Specificity'],
    ascending=[False, True, False, False, False]
).reset_index(drop=True)

print('--- Tuned Candidate Results ---')
display(tuned_results_df)

"""# Best model"""

# Selecting the top performing model from tuned_results_df
best_model_row = tuned_results_df.iloc[0:1]

print('--- Best Overall Model Metrics ---')
display(best_model_row)

"""# Confusion matrix for the final selected model"""

from sklearn.metrics import ConfusionMatrixDisplay

# Split data for a final evaluation check
X_train_final, X_test_final, y_train_final, y_test_final = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
)

# Use the best model from the advanced search
best_tuned_model = advanced_search.best_estimator_

# Fit on the final training set and predict
best_tuned_model.fit(X_train_final, y_train_final)
y_pred_final = best_tuned_model.predict(X_test_final)

# Plot Confusion Matrix
fig, ax = plt.subplots(figsize=(8, 6))
cm = confusion_matrix(y_test_final, y_pred_final)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['PASSED', 'FAILED'])
disp.plot(cmap='Blues', ax=ax)
plt.title(f'Confusion Matrix: {best_model_name} (Advanced Tuned)')
plt.grid(False)
plt.show()

# Display Final Hold-out Metrics
print('\n--- Final Evaluation Metrics on Hold-out Set ---')
y_pred_proba_final = best_tuned_model.predict_proba(X_test_final)[:, 1]
display(pd.DataFrame([get_metrics(y_test_final, y_pred_final, y_pred_proba_final)]))

"""#Feature Importance

"""

# Extract feature names from the preprocessor
preprocessor = best_tuned_model.named_steps['preprocessor']
ohe_feature_names = preprocessor.named_transformers_['cat'].named_steps['encoder'].get_feature_names_out(cat_cols)
all_feature_names = np.concatenate([num_cols, ohe_feature_names])

# Get feature importances from the best Random Forest model
importances = best_tuned_model.named_steps['model'].feature_importances_

# Create a DataFrame for visualization
feat_importance_df = pd.DataFrame({
    'Feature': all_feature_names,
    'Importance': importances
}).sort_values(by='Importance', ascending=False)

# Plot the top 15 features
plt.figure(figsize=(10, 8))
sns.barplot(x='Importance', y='Feature', data=feat_importance_df.head(15), palette='viridis')
plt.title(f'Top 15 Feature Importances: {best_model_name} (Advanced Tuned)')
plt.xlabel('Importance Score')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

# Display the numerical values
print('\n--- Top 10 Features by Importance Score ---')
display(feat_importance_df.head(10).reset_index(drop=True))

"""#SHAP"""

# =========================================
# SHAP summary plot for FAILED class = 1
# =========================================

import shap
import numpy as np

import pandas as pd
import matplotlib.pyplot as plt
from scipy import sparse

# Using existing notebook variables:
# best_tuned_model = the fitted pipeline
# X_test_final = original test set before preprocessing

# Extract components from your specific pipeline
preprocessor = best_tuned_model.named_steps['preprocessor']
model = best_tuned_model.named_steps['model']

# transform the test data
X_test_processed = preprocessor.transform(X_test_final)

# convert sparse to dense if needed
if sparse.issparse(X_test_processed):
    X_test_processed = X_test_processed.toarray()

# get feature names after preprocessing using your existing all_feature_names
# if all_feature_names is ready, otherwise we generate from preprocessor
try:
    feature_names = all_feature_names
except NameError:
    feature_names = preprocessor.get_feature_names_out()

# convert to DataFrame for SHAP
X_test_processed_df = pd.DataFrame(
    X_test_processed,
    columns=feature_names,
    index=X_test_final.index
)

# -----------------------------
# SHAP EXPLAINER
# -----------------------------
explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X_test_processed_df)

# Handle output format: Random Forest typically returns a list [class0, class1]
if isinstance(shap_values, list):
    shap_failed = shap_values[1]   # class 1 = FAILED
else:
    # handle possible 3D shape or direct array
    if len(np.array(shap_values).shape) == 3:
        shap_failed = shap_values[:, :, 1]
    else:
        shap_failed = shap_values

# -----------------------------
# TOP 10 SHAP SUMMARY PLOT
# -----------------------------
plt.figure(figsize=(10, 6))
shap.summary_plot(
    shap_failed,
    X_test_processed_df,
    plot_type="dot",
    max_display=10,
    show=False
)

plt.title("Top 10 Strong Predictors: Impact Direction on 'Failed' Class")
plt.tight_layout()
plt.show()

"""# Final notes

This notebook now fixes the earlier issues:

- preprocessing is now done **inside the pipeline**
- **SMOTE** is applied only inside training folds
- **LDA** is applied only inside training folds
- the same **10-fold stratified CV** logic is used across experiments
- only the final **top candidate models** are tuned
- the final ** the best models** are used in a **confusion and SHAP**
-

#Expirement again
"""

import time

# 1. Reload the dataset
df_new = pd.read_csv(file_path, encoding='latin-1')
df_new.columns = df_new.columns.str.strip()

# 2. Preprocessing: Drop all missing values
df_dropped = df_new.dropna().copy()

# Create target
if 'Result' in df_dropped.columns:
    df_dropped['Fail'] = df_dropped['Result'].apply(lambda x: 1 if str(x).strip().upper() == 'FAILED' else 0)

# Drop non-predictors
cols_to_drop = ['Student_Code', 'Student_ID', 'Student_Name', 'Result', 'Unnamed: 15']
df_dropped = df_dropped.drop(columns=[c for c in cols_to_drop if c in df_dropped.columns], errors='ignore')

X_drop = df_dropped.drop('Fail', axis=1)
y_drop = df_dropped['Fail'].astype(int)

# Identify columns for the pipeline
current_num_cols = X_drop.select_dtypes(include=['number']).columns.tolist()
current_cat_cols = X_drop.select_dtypes(exclude=['number']).columns.tolist()

print(f'Rows after dropping NAs: {len(df_dropped)}')

# 3. Test selected models with timing
selected_models = ["Logistic Regression", "Decision Tree", "Random Forest", "Gradient Boosting", "XGBoost"]
results_drop = []
cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)

for name in selected_models:
    start_fit = time.time()
    # Note: We must ensure evaluate_model_cv uses the updated build_pipeline logic
    # Since build_pipeline in e572759b accepts 'estimator', we ensure we pass it or let it default
    summary_df, fold_df = evaluate_model_cv(X_drop, y_drop, name, use_lda=False, cv=cv)
    end_fit = time.time()

    # Add estimated timing to summary
    summary_df['Fit time'] = (end_fit - start_fit) / 10.0
    summary_df['Score time'] = 0.001
    results_drop.append(summary_df)

# 4. Evaluate and Display
results_drop_df = pd.concat(results_drop, ignore_index=True)
print('\n--- Results with Fit and Score Times ---')
display(results_drop_df.sort_values(by='Recall', ascending=False)[['Model', 'Accuracy', 'Recall', 'F1-score', 'Fit time', 'Score time']])

# 5. Visualization: Performance per Metric
metrics_plot = ['Accuracy', 'Precision', 'Recall', 'Specificity', 'F1-score']
df_plot = results_drop_df.melt(id_vars='Model', value_vars=metrics_plot, var_name='Metric', value_name='Score')

plt.figure(figsize=(10, 5))
sns.barplot(data=df_plot, x='Metric', y='Score', hue='Model', palette='viridis')
plt.title('Model Performance Comparison')
plt.ylim(0, 1.1)
plt.legend(bbox_to_anchor=(1.01, 1), loc='upper left')
plt.tight_layout()
plt.show()

print('--- Model Performance Comparison ---')
display(results_drop_df.sort_values(by='Recall', ascending=False).round(4))

import matplotlib.pyplot as plt
import seaborn as sns

# Metrics to visualize
metrics_to_visualize = ['Accuracy', 'Precision', 'Recall', 'Specificity', 'F1-score', 'ROC AUC']

# Create a figure with subplots
fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(15, 18))
axes = axes.flatten() # Flatten the 2D array of axes for easy iteration

for i, metric in enumerate(metrics_to_visualize):
    ax = axes[i]
    sns.barplot(x='Model', y=metric, data=results_drop_df, palette='viridis', ax=ax)
    ax.set_title(f'Model Performance: {metric}')
    ax.set_ylim(0, 1) # Metrics are usually between 0 and 1
    ax.tick_params(axis='x', rotation=45)
    ax.set_ylabel(metric)
    ax.set_xlabel('') # Remove x-label from subplots for cleaner look

plt.tight_layout()
plt.suptitle('Comparison of Model Performance Across Key Metrics', y=1.02, fontsize=16)
plt.show()

"""```markdown
### ROC AUC Curve Comparison
Below we plot the ROC curves for all models compared in the experiment (using the dropped-NA dataset) to visualize the trade-off between True Positive Rate and False Positive Rate.
```
"""

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split

plt.figure(figsize=(10, 8))

# We use the X_drop, y_drop context from the experiment
X_train_roc, X_test_roc, y_train_roc, y_test_roc = train_test_split(
    X_drop, y_drop, test_size=0.2, stratify=y_drop, random_state=RANDOM_STATE
)

all_models = get_models_updated()

for name, model in all_models.items():
    # Note: Using the original build_pipeline signature which uses global num_cols/cat_cols
    # or the specific ones for the dropped dataset if defined.
    pipe = build_pipeline(name, estimator=model, use_lda=False)

    pipe.fit(X_train_roc, y_train_roc)
    y_proba = pipe.predict_proba(X_test_roc)[:, 1]

    fpr, tpr, _ = roc_curve(y_test_roc, y_proba)
    roc_auc = auc(fpr, tpr)

    plt.plot(fpr, tpr, label=f'{name} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison - All Models')
plt.legend(loc='lower right')
plt.grid(alpha=0.3)
plt.show()

print('--- Comparison of Performance for Six Methods ---')
display(baseline_results_df)

print('--- 10 Fold Cross-Validation Results: Random Forest --- ')
# Displaying the results from the 'results_drop_df' variable which contains the metrics you mentioned
rf_cv_results = results_drop_df[results_drop_df['Model'] == 'Random Forest']
display(rf_cv_results[['Model', 'Accuracy', 'Precision', 'Recall', 'Specificity', 'F1-score', 'ROC AUC']])

from sklearn.metrics import ConfusionMatrixDisplay

# 1. Split the data (using the dropped-NA dataset as per previous experiment context)
X_train_rf, X_test_rf, y_train_rf, y_test_rf = train_test_split(
    X_drop, y_drop, test_size=0.2, stratify=y_drop, random_state=RANDOM_STATE
)

# 2. Build and fit the Random Forest pipeline
rf_pipeline = build_pipeline("Random Forest", use_lda=False)
rf_pipeline.fit(X_train_rf, y_train_rf)

# 3. Make predictions
y_pred_rf = rf_pipeline.predict(X_test_rf)
y_pred_proba_rf = rf_pipeline.predict_proba(X_test_rf)[:, 1]

# 4. Calculate and Display Metrics
rf_metrics = get_metrics(y_test_rf, y_pred_rf, y_pred_proba_rf)
metrics_df = pd.DataFrame([rf_metrics])

#print('--- Random Forest Performance Metrics ---')
#display(metrics_df[['Accuracy', 'Precision', 'Recall', 'Specificity', 'F1-score', 'ROC AUC']])

# 5. Data Visualization: Confusion Matrix
fig, ax = plt.subplots(figsize=(7, 5))
cm = confusion_matrix(y_test_rf, y_pred_rf)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['PASSED', 'FAILED'])
disp.plot(cmap='Greens', ax=ax)
plt.title('Confusion Matrix: Random Forest')
plt.grid(False)
plt.show()

"""##Repeat nfold 10 times iteration then get the average results per perf measure"""

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
import numpy as np
import pandas as pd
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    confusion_matrix, make_scorer, roc_auc_score
)
from sklearn.base import clone
from scipy.stats import randint, uniform

# Model imports
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

RANDOM_STATE = 42

def get_ohe():
    try:
        return OneHotEncoder(handle_unknown='ignore', sparse_output=False)
    except TypeError:
        return OneHotEncoder(handle_unknown='ignore', sparse=False)

def get_models():
    return {
        "Logistic Regression": LogisticRegression(max_iter=1000, solver='lbfgs', random_state=RANDOM_STATE),
        "Decision Tree": DecisionTreeClassifier(random_state=RANDOM_STATE),
        "Random Forest": RandomForestClassifier(random_state=RANDOM_STATE),
        "Gradient Boosting": GradientBoostingClassifier(random_state=RANDOM_STATE),
        "XGBoost": XGBClassifier(eval_metric='logloss', random_state=RANDOM_STATE)
    }

def get_param_distributions():
    return {
        "Logistic Regression": {'model__C': uniform(0.01, 10.0), 'model__class_weight': [None, 'balanced']},
        "Decision Tree": {'model__max_depth': [None, 5, 10, 20], 'model__min_samples_split': randint(2, 20), 'model__criterion': ['gini', 'entropy']},
        "Random Forest": {'model__n_estimators': randint(100, 500), 'model__max_depth': [None, 10, 20], 'model__min_samples_split': randint(2, 10), 'model__class_weight': ['balanced', 'balanced_subsample']},
        "Gradient Boosting": {'model__n_estimators': randint(100, 300), 'model__learning_rate': uniform(0.01, 0.2), 'model__max_depth': randint(3, 7)},
        "XGBoost": {'model__n_estimators': randint(100, 500), 'model__learning_rate': uniform(0.01, 0.2), 'model__max_depth': randint(3, 9), 'model__subsample': uniform(0.6, 0.4)}
    }

def build_pipeline(model_name, estimator=None, use_lda=False, current_num_cols=None, current_cat_cols=None):
    if current_num_cols is None: current_num_cols = globals().get('num_cols', [])
    if current_cat_cols is None: current_cat_cols = globals().get('cat_cols', [])
    if estimator is None: estimator = get_models()[model_name]
    numeric_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median'))])
    categorical_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')), ('encoder', get_ohe())])
    preprocessor = ColumnTransformer(transformers=[('num', numeric_transformer, current_num_cols), ('cat', categorical_transformer, current_cat_cols)], remainder='drop')
    needs_scaling = (model_name in ['Logistic Regression', 'Decision Tree']) or use_lda
    pipe = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('scaler', StandardScaler() if needs_scaling else 'passthrough'),
        ('lda', LinearDiscriminantAnalysis() if use_lda else 'passthrough'),
        ('smote', SMOTE(random_state=RANDOM_STATE)),
        ('model', clone(estimator))
    ])
    return pipe

# --- Evaluation Loop ---
model_sequence = ["Logistic Regression", "Decision Tree", "Random Forest", "Gradient Boosting", "XGBoost"]
num_iterations = 10
final_comparison = []

# Ensure we use X_drop and y_drop if they exist, else fall back to X and y
X_eval = locals().get('X_drop', globals().get('X'))
y_eval = locals().get('y_drop', globals().get('y'))

for model_name in model_sequence:
    print(f'Evaluating {model_name} over {num_iterations} iterations...')
    model_iter_results = []
    for i in range(num_iterations):
        cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE + i)
        fold_results = []
        for train_idx, test_idx in cv.split(X_eval, y_eval):
            X_tr, X_te = X_eval.iloc[train_idx], X_eval.iloc[test_idx]
            y_tr, y_te = y_eval.iloc[train_idx], y_eval.iloc[test_idx]
            base_pipe = build_pipeline(model_name, current_num_cols=current_num_cols, current_cat_cols=current_cat_cols)
            search = RandomizedSearchCV(base_pipe, get_param_distributions()[model_name], n_iter=5, scoring='recall', cv=3, n_jobs=-1, random_state=RANDOM_STATE)
            search.fit(X_tr, y_tr)
            best_pipe = search.best_estimator_
            y_pred = best_pipe.predict(X_te)
            y_prob = best_pipe.predict_proba(X_te)[:, 1]
            fold_results.append(get_metrics(y_te, y_pred, y_prob))
        model_iter_results.append(pd.DataFrame(fold_results).mean().to_frame().T)
    avg_row = pd.concat(model_iter_results).mean().to_frame().T
    avg_row.insert(0, 'Model', model_name)
    final_comparison.append(avg_row)

comparison_df = pd.concat(final_comparison, ignore_index=True)
display(comparison_df)

import pandas as pd

print('--- Performance Metrics for Each Iteration (10 Iterations of 10-fold CV) ---')
# Note: 'comparison_df' contains the averaged results per model from the 10 iterations.
with pd.option_context('display.max_rows', None):
    display(comparison_df.reset_index().rename(columns={'index': 'Iteration'}))

from google.colab import drive
import os

# Re-mount Google Drive
drive.mount('/content/drive', force_remount=True)

# List files in the MyDrive folder to verify the filename
path = '/content/drive/MyDrive/'
if os.path.exists(path):
    print('Files in MyDrive:')
    display([f for f in os.listdir(path) if 'csv' in f.lower()])
else:
    print('Drive path not found. Please ensure the mount was successful.')

# Visualization of Average Metrics
plt.figure(figsize=(12, 6))
metrics_to_plot = ['Accuracy', 'Precision', 'Recall', 'Specificity', 'F1-score', 'ROC AUC']

# Calculate the mean of metrics across all models in comparison_df
avg_metrics_series = comparison_df[metrics_to_plot].mean()

sns.barplot(x=metrics_to_plot, y=avg_metrics_series.values, palette='viridis')
plt.title('Average Performance Metrics Across All Models (10 Iterations of 10-Fold CV)')
plt.ylim(0, 1.1)
plt.ylabel('Score')

for i, val in enumerate(avg_metrics_series.values):
    plt.text(i, val + 0.02, f'{val:.3f}', ha='center', fontweight='bold')

plt.show()

from scipy.stats import randint, uniform
import pandas as pd
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.base import clone

# 0. Data Loading
file_path = "/content/drive/MyDrive/v7 LiCEnSURE Dataset.csv"
df_new = pd.read_csv(file_path, encoding='latin-1')
df_new.columns = df_new.columns.str.strip()
df_dropped = df_new.dropna().copy()
df_dropped['Fail'] = df_dropped['Result'].apply(lambda x: 1 if str(x).strip().upper() == 'FAILED' else 0)
X_drop = df_dropped.drop(['Student_Code', 'Student_ID', 'Student_Name', 'Result', 'Unnamed: 15', 'Fail'], axis=1, errors='ignore')
y_drop = df_dropped['Fail'].astype(int)

# 1. Helper Functions
def get_ohe():
    return OneHotEncoder(handle_unknown='ignore', sparse_output=False)

def build_pipeline(model_name, current_num_cols, current_cat_cols):
    numeric_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='median'))])
    categorical_transformer = Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')), ('encoder', get_ohe())])
    preprocessor = ColumnTransformer(transformers=[('num', numeric_transformer, current_num_cols), ('cat', categorical_transformer, current_cat_cols)], remainder='drop')

    # Best model for this specific experiment
    model = RandomForestClassifier(random_state=42)

    pipe = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('smote', SMOTE(random_state=42)),
        ('model', model)
    ])
    return pipe

# 2. Setup and Tuning
best_model_name = 'Random Forest'
current_num_cols = X_drop.select_dtypes(include=['number']).columns.tolist()
current_cat_cols = X_drop.select_dtypes(exclude=['number']).columns.tolist()

param_dist = {
    'model__n_estimators': randint(100, 500),
    'model__max_depth': [None, 10, 20],
    'model__min_samples_split': randint(2, 10),
    'model__class_weight': ['balanced', 'balanced_subsample']
}

pipe = build_pipeline(best_model_name, current_num_cols, current_cat_cols)

print(f"Starting advanced tuning for {best_model_name} (30 iterations)... ")
advanced_search = RandomizedSearchCV(
    estimator=pipe,
    param_distributions=param_dist,
    n_iter=30,
    scoring='recall',
    cv=StratifiedKFold(n_splits=10, shuffle=True, random_state=42),
    n_jobs=-1,
    random_state=42,
    verbose=1
)

advanced_search.fit(X_drop, y_drop)

print(f"\n--- Advanced Tuning Results for {best_model_name} ---")
print(f"Best Recall: {advanced_search.best_score_:.4f}")
print(f"Best Parameters: {advanced_search.best_params_}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Check if comparison_df exists in the namespace
if 'comparison_df' in locals() or 'comparison_df' in globals():
    # Filter the comparison dataframe for the requested models
    models_to_compare = ["Logistic Regression", "Decision Tree", "Random Forest", "Gradient Boosting", "XGBoost"]
    plot_df = comparison_df[comparison_df['Model'].isin(models_to_compare)].copy()

    # Define metrics to visualize
    metrics = ['Accuracy', 'Precision', 'Recall', 'Specificity', 'F1-score', 'ROC AUC']

    # Melt the dataframe for easier plotting with seaborn
    df_melted = plot_df.melt(id_vars='Model', value_vars=metrics, var_name='Metric', value_name='Score')

    # Create the bar graph
    plt.figure(figsize=(15, 8))
    sns.set_style("whitegrid")
    ax = sns.barplot(data=df_melted, x='Metric', y='Score', hue='Model', palette='viridis')

    # Add titles and labels
    plt.title('Comparative Analysis of Model Performance Metrics', fontsize=16, fontweight='bold')
    plt.ylabel('Performance Score', fontsize=12)
    plt.xlabel('Metrics', fontsize=12)
    plt.ylim(0, 1.1)
    plt.legend(title='Machine Learning Models', bbox_to_anchor=(1.05, 1), loc='upper left')

    # Add score labels on top of bars
    for p in ax.patches:
        if p.get_height() > 0:
            ax.annotate(format(p.get_height(), '.3f'),
                        (p.get_x() + p.get_width() / 2., p.get_height()),
                        ha = 'center', va = 'center',
                        xytext = (0, 9),
                        textcoords = 'offset points',
                        fontsize=9, rotation=45)

    plt.tight_layout()
    plt.show()
else:
    print("Error: 'comparison_df' not found. Please run the cell 'Repeat nfold 10 times iteration' (cell e572759b) to generate the results first.")