'use client'
import { useState } from 'react'
import { FileText, Download, Eye, Filter, ChevronDown } from 'lucide-react'

const reports = [
  { id: 1, title: 'Q1 2024 Predictive Report', type: 'Predictive', date: '2024-01-22', records: 83, generatedBy: 'Chairman', status: 'Ready' },
  { id: 2, title: 'Batch 2024 Jan-A Summary', type: 'Upload Summary', date: '2024-01-22', records: 45, generatedBy: 'Staff User 1', status: 'Ready' },
  { id: 3, title: 'Batch 2024 Jan-B Summary', type: 'Upload Summary', date: '2024-01-22', records: 38, generatedBy: 'Staff User 2', status: 'Ready' },
  { id: 4, title: 'Model Performance Report – RF v2', type: 'Model Performance', date: '2024-01-20', records: null, generatedBy: 'System', status: 'Ready' },
  { id: 5, title: 'AY 2023 Annual Board Exam Analysis', type: 'Annual', date: '2023-12-15', records: 120, generatedBy: 'Chairman', status: 'Ready' },
]

const typeColors: Record<string, string> = {
  'Predictive': 'bg-blue-50 text-blue-700',
  'Upload Summary': 'bg-purple-50 text-purple-700',
  'Model Performance': 'bg-orange-50 text-orange-700',
  'Annual': 'bg-green-50 text-green-700',
}

export default function ReportsPage() {
  const [generating, setGenerating] = useState(false)
  const [success, setSuccess] = useState(false)

  const handleGenerate = async () => {
    setGenerating(true)
    await new Promise(r => setTimeout(r, 1500))
    setGenerating(false)
    setSuccess(true)
    setTimeout(() => setSuccess(false), 3000)
  }

  return (
    <div className="p-8">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Reports</h1>
          <p className="text-gray-500 text-sm mt-1">Generate and download predictive analysis reports</p>
        </div>
        <button onClick={handleGenerate} disabled={generating}
          className="flex items-center gap-2 px-4 py-2.5 rounded-lg text-sm font-semibold text-white transition-all hover:opacity-90 disabled:opacity-70"
          style={{ backgroundColor: '#0B2C5D' }}>
          <FileText className="w-4 h-4" />
          {generating ? 'Generating...' : 'Generate New Report'}
        </button>
      </div>

      {success && (
        <div className="mb-5 px-4 py-3 rounded-lg text-sm font-medium bg-green-50 text-green-700 border border-green-200">
          ✓ Report generated successfully and is ready for download.
        </div>
      )}

      {/* Report type cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        {[
          { label: 'Predictive Reports', count: 2, color: '#0B2C5D', bg: '#e8edf5' },
          { label: 'Upload Summaries', count: 2, color: '#7c3aed', bg: '#f5f3ff' },
          { label: 'Model Performance', count: 1, color: '#ea580c', bg: '#fff7ed' },
          { label: 'Annual Reports', count: 1, color: '#16a34a', bg: '#f0fdf4' },
        ].map(({ label, count, color, bg }) => (
          <div key={label} className="bg-white rounded-xl p-4 shadow-sm border border-gray-100">
            <div className="text-2xl font-bold" style={{ color }}>{count}</div>
            <div className="text-gray-500 text-sm mt-1">{label}</div>
            <div className="w-8 h-1 rounded-full mt-2" style={{ backgroundColor: color }} />
          </div>
        ))}
      </div>

      {/* Reports table */}
      <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="px-5 py-4 border-b border-gray-100 flex items-center justify-between">
          <h3 className="font-semibold text-gray-700">All Reports</h3>
          <button className="flex items-center gap-1.5 text-gray-500 text-sm hover:text-gray-700">
            <Filter className="w-4 h-4" /> Filter <ChevronDown className="w-3 h-3" />
          </button>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-100 bg-gray-50">
                <th className="text-left px-5 py-3 font-semibold text-gray-600 text-xs uppercase">Report</th>
                <th className="text-left px-5 py-3 font-semibold text-gray-600 text-xs uppercase">Type</th>
                <th className="text-left px-5 py-3 font-semibold text-gray-600 text-xs uppercase">Date</th>
                <th className="text-left px-5 py-3 font-semibold text-gray-600 text-xs uppercase">Records</th>
                <th className="text-left px-5 py-3 font-semibold text-gray-600 text-xs uppercase">Generated By</th>
                <th className="text-left px-5 py-3 font-semibold text-gray-600 text-xs uppercase">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {reports.map(r => (
                <tr key={r.id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-5 py-3.5">
                    <div className="flex items-center gap-2.5">
                      <FileText className="w-4 h-4 text-gray-400 flex-shrink-0" />
                      <span className="font-medium text-gray-800">{r.title}</span>
                    </div>
                  </td>
                  <td className="px-5 py-3.5">
                    <span className={`px-2.5 py-1 rounded-full text-xs font-medium ${typeColors[r.type] || 'bg-gray-100 text-gray-600'}`}>
                      {r.type}
                    </span>
                  </td>
                  <td className="px-5 py-3.5 text-gray-500">{r.date}</td>
                  <td className="px-5 py-3.5 text-gray-500">{r.records ?? '—'}</td>
                  <td className="px-5 py-3.5 text-gray-500">{r.generatedBy}</td>
                  <td className="px-5 py-3.5">
                    <div className="flex items-center gap-2">
                      <button className="p-1.5 rounded-lg text-gray-400 hover:text-blue-600 hover:bg-blue-50 transition-all">
                        <Eye className="w-4 h-4" />
                      </button>
                      <button className="p-1.5 rounded-lg text-gray-400 hover:text-green-600 hover:bg-green-50 transition-all">
                        <Download className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}
